### PR TITLE
Added logger initialization

### PR DESCRIPTION
**Pull request by anurodh-ti**
1.

### CODE REVIEW

**Comment by arleif-dfactory** [comment]
@anurodh-ti WHy was this even necessary?

1) You should have started the design with a link to an ITD titled "Build our own logging framework because all the frameworks written by other smart people doesn't fit our needs" Inside that ITD the reader should see a comparison with frameworks like https://github.com/rs/zerolog, https://github.com/Sirupsen/logrus etc and explain why we simply can't use one of them. I find it very hard to understand why you chose to build your own framework.
2) Why do you want to log to files vs to the console?

If I was writing this issue it would have been structured in the following way
1) What we need from the logger.
   - Log user facing logs to the console.
   - Log all logs including debug logs to a separate debug log file that the end user is not expected to consume and can be sent to the dev team with bug reports.
   - User facing logs should be neatly formatted and not be structured logs with json in them that is hard to read
   - The location of the log file should have a default value, but the user should be able to override it via command line params
   - A new debug log file should be written per execution of the orchestrator, and must not be time-based and must never have logs of multiple executions in the same file.
   - Debug logs need timestamps and source file name and line numbers
   - User facing logs must not have any reference to source files and line number, only timestamp and the stage of processing.
2) Which logging framework to use? Not spending too much time on this decision as it is easy to change later if necessary. I chose to use XYZ because it supports non-structured logging and the basic file writing that I need.

Definition of done:
- Orchestrator (cli tool) can take the log folder as input and override the default
- When the cli is run, the logger is initialized, two logs are printed to the console (starting executions, completed execution), and these two logs + one additional debug log is printed in a new file created in the debug folder
- All logs are printed in the appropriate format.

**Comment by anurodh-ti** [comment]
@arleif-dfactory 
1. Why we made a separate framework:- We thought the inbuilt logger in go mostly suffices our needs, just that we need to log 
into files and we need to have three levels at which we wanna log. So for that, I just made that initialization to add these functionalities to the inbuilt go logger.
But looking at the things you have mentioned, there are many more things which need to be addressed apart from these 
things, mostly for which we maybe need to re-evaluate this decision(considering logging Github repos). 
And adding to that I also thought that it is not of much importance to spend much time on this decision now because this can be changed afterward if necessary and also our requirements were getting fulfilled by the current framework(logging in a text-based non-structered format, with three levels and logging to the files), so we went with this framework only.

2. Why do we want to log to files than to the console:- We thought it is better to log in the files because logging to the console 
means giving insights into what is happening inside the code directly to the user (Which user doesnt even no properly, he is just using our product as a whole, he doesn't care what's inside). The importance of logging could have come into play as you have mentioned sending the bug reports to the dev team using files. That's why we went on to use file only.

Also, these things could also be implemented inside our framework but If we have something which has these things already it(existing Github repos) is not beneficial to waste time adding to our code to increase customizability, So we need to re-evaluate our decision seeing the important points. I will try to find a suitable logger for this (most loggers apart from logrus, log in json format to the files, we need to see this as well) and how could we incorporate all these things to our logger.

**Comment by arleif-dfactory** [comment]
Long message but I'm not sure what your conclusion is. I'm assuming it is
- you agree that you don't need to write you own logging framework and will find and use a good and stable go logging framework.
- not writing a logging framework means you won't even need to write a single log class mostly, you will just invoke the logger wherever required.

If the above is true then all you needed to do was delete the stuff you added to the issue description and update it to some new content. No need for long justification, you can just reply to my comment saying "issue updated". In order to help you, I proposed what the issues should look like. start with that and make whatever changes you need to it. I'd like to know specifically which parts of my proposal you are using and what you wish to change.

**Comment by anurodh-ti** [comment]
I checked for all the points you mentioned and am adding what I found is feasible:-
1). We can log to user-facing logs to console and log to files through one command but writing to the filesystem is directly not possible through these loggers, we need to use hooks for this.
2). User-facing logs would be in direct text format and log-to-files would be in a structured format(JSON).
3). Writing to a separate debug file for each execution is possible but its naming is going to be time-based.
4). We will customize user-facing and debug logs differently.
5). I found, no directly provided functionality even through hooks to override the log file location dynamically. But we can by ourselves write some code and try to pass the location as string in that function.
5). For the above things we need to include some code as our initialization ( as we are not directly logging in same format to console and file and not directly using multi-writer).

I will be adding my code according to these findings.

**Pull request merged**
